server:
  servlet:
    encoding:
      force-request: true
      force-response: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
    # 解决中文乱码出现?? 的问题
  port: 8080
spring:
  application:
    name: soul-trail
  datasource:
    # 本地开发用主实例外网地址；部署到阿里云同 VPC 后改为内网地址
    #    url: jdbc:mysql://rm-bp1cx5758n1ea967j3o.mysql.rds.aliyuncs.com:3306/soultraildb?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true

    # 内网地址
    url: "jdbc:mysql://rm-bp1cx5758n1ea967j.mysql.rds.aliyuncs.com:3306/soultraildb?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true"

    username: soultrail
    password: Soul1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    # HikariCP 为 Spring Boot 默认连接池，以下为可选调优项 (先不管)
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.sixth.soul_trail.pojo
  configuration:
    map-underscore-to-camel-case: true
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 开发期打印 SQL，上线前删掉这行